### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vorvac** [pcottle/MSOutlookit#1]
Hey pcottle, on your new MSOutlookit page (http://pcottle.github.io/MSOutlookit/) you've added a link to the old version which is broken. I'm guessing It should be (http://pcottle.github.io/MSOutlookit/2004/) not (http://pcottle.github.io/2004/index.html)

Thanks

Edit: looks like you've already done so

**Comment by pcottle** [comment]
Nah you're totally right -- it should be a relative link. lemme try that

**Comment by pcottle** [comment]
Fixed!

**Comment by waldyrious** [comment]
I can confirm it didn't work for me before (even after the "looks like you've already done so" commit, e67e309). With the new commit, fc99e91, it works indeed :)

**Comment by vorvac** [comment]
Awesome, thanks!
