### ISSUE TITLE
Never finishes loading

### ISSUE THREAD

**Issue by alvarow-no** [pcottle/MSOutlookit#10]
It seems like something is wrong with MSOutlookit. Tried accessing it several times today and yesterday. The website itself gets loaded, but it seems like the actual reddit posts don't load properly as the 'loading wheel' just keeps on going infinitely.

Any solution? Thanks in advance

**Comment by pcottle** [comment]
![Screenshot 2023-07-25 at 8 31 25 AM](https://github.com/pcottle/MSOutlookit/assets/1135007/84286935-d3fc-4e70-b4b5-7301e1952d3d)

**Comment by pcottle** [comment]
Seems to be working for me, including loading the stories. I would check the JS console and see if you spot any obvious errors
