### ISSUE TITLE
user cant change r/ block

### ISSUE THREAD

**Issue by EdiqC** [pcottle/MSOutlookit#8]
user cant change r/ block

**Comment by EdiqC** [comment]
new email icon - entry "name " : it will shows /r block in inbox tab

**Comment by pcottle** [comment]
<img width="886" alt="Screen Shot 2021-08-26 at 9 07 18 AM" src="https://user-images.githubusercontent.com/1135007/130988159-ca9eb1fa-b55e-4939-b956-bf9ef5aeb5cd.png">
<img width="643" alt="Screen Shot 2021-08-26 at 9 07 33 AM" src="https://user-images.githubusercontent.com/1135007/130988191-788254bf-ff55-4fb2-b559-108c9949d661.png">
think you have to enter it without the /r/
